apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-v1d0
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-v1d0
    app.kubernetes.io/part-of: ci10t-786-0029-app
  name: devfile-sample-v1d0
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-v1d0
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-v1d0
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0029-tenant/ci10t-786-0029-app/devfile-sample-v1d0@sha256:3717cfc11c4955ce75f9795938616f25f107cb5bfba878ee27c9c09653dbfec3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
